<a href="https://colab.research.google.com/github/tomifarall/Orga-Datos-Tp2/blob/master/modelos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from wordcloud import WordCloud
import re
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import mean_squared_error

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import euclidean_distances

import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn import tree
#from catboost import CatBoostRegressor
#!pip install catboost

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
#ESTO NO LO EJECUTEN SI UTILIZAN UNA VERSION DE PC , YO LO HAGO PARA PODER USAR EL TRAIN DE MI DRIVE,Y USAR EL GITHUB ONLINE
# Import PyDrive and associated libraries.
# This only needs to be done once per notebook.
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# Authenticate and create the PyDrive client.
# This only needs to be done once per notebook.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [3]:
# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = '1RJH-BaqHHtZzrSgu6yUVc8bRXcfev9tB'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('train_1.csv')

In [4]:
# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = '1sivn_RJ13uL13DmmB_G03yJRJWw_b2He'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('train_2.csv')

In [5]:
# Download a file based on its file ID.
#
# A file ID looks like: laggVyWshwcyP6kEI-y_W3P8D26sz
file_id = '1eO4Vnym1_XoOx8yL1UC9WmZJvROH4dt_'
downloaded = drive.CreateFile({'id': file_id})
downloaded.GetContentFile('train_3.csv')

In [89]:
train_1 = pd.read_csv('train_1.csv')
train_2= pd.read_csv('train_2.csv')
train_3=pd.read_csv('train_3.csv')

In [59]:
train_3.head(10)

   Unnamed: 0  id  ... target                                         clean_text
0           0  48  ...      1                     bbcmtd wholesale market ablaze
1           1  49  ...      0                    always try bring heavy metal rt
2           2  50  ...      1  africanbaze breaking newsnigeria flag set abla...
3           3  52  ...      0                                     cry set ablaze
4           4  53  ...      0               plus side look sky last night ablaze
5           5  54  ...      0  phdsquares mufc theyve built much hype around ...
6           6  55  ...      1                        inec office abia set ablaze
7           7  57  ...      0                                        ablaze lord
8           8  59  ...      0                                         check nsfw
9           9  62  ...      0  awesome time visiting cfc head office ancop si...

[10 rows x 7 columns]

In [90]:
train_3=train_3.drop( columns='Unnamed: 0')

In [9]:
!pip install gensim
from gensim.models import KeyedVectors

Requirement already satisfied: gensim in /usr/local/lib/python3.6/dist-packages (3.6.0)
Requirement already satisfied: numpy>=1.11.3 in /usr/local/lib/python3.6/dist-packages (from gensim) (1.18.5)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.6/dist-packages (from gensim) (2.1.0)
Requirement already satisfied: scipy>=0.18.1 in /usr/local/lib/python3.6/dist-packages (from gensim) (1.4.1)
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from gensim) (1.15.0)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from smart-open>=1.2.1->gensim) (2.23.0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.6/dist-packages (from smart-open>=1.2.1->gensim) (1.14.24)
Requirement already satisfied: boto in /usr/local/lib/python3.6/dist-packages (from smart-open>=1.2.1->gensim) (2.49.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->smart-open>=1.2.1->gensim) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->smart-open>=1.2.1->gensim) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->smart-open>=1.2.1->gensim) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->smart-open>=1.2.1->gensim) (1.24.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.6/dist-packages (from boto3->smart-open>=1.2.1->gensim) (0.10.0)
Requirement already satisfied: botocore<1.18.0,>=1.17.24 in /usr/local/lib/python3.6/dist-packages (from boto3->smart-open>=1.2.1->gensim) (1.17.24)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from boto3->smart-open>=1.2.1->gensim) (0.3.3)
Requirement already satisfied: docutils<0.16,>=0.10 in /usr/local/lib/python3.6/dist-packages (from botocore<1.18.0,>=1.17.24->boto3->smart-open>=1.2.1->gensim) (0.15.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.6/dist-packages (from botocore<1.18.0,>=1.17.24->boto3->smart-open>=1.2.1->gensim) (2.8.1)

In [10]:
!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

--2020-07-29 12:35:56--  https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.39.70
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.39.70|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1647046227 (1.5G) [application/x-gzip]
Saving to: ‘/root/input/GoogleNews-vectors-negative300.bin.gz’

GoogleNews-vectors- 100%[===================>]   1.53G  66.1MB/s    in 34s

2020-07-29 12:36:30 (45.9 MB/s) - ‘/root/input/GoogleNews-vectors-negative300.bin.gz’ saved [1647046227/1647046227]

In [11]:
EMBEDDING_FILE = '/root/input/GoogleNews-vectors-negative300.bin.gz' # from above
word2vec = KeyedVectors.load_word2vec_format(EMBEDDING_FILE, binary=True)

/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py:254: UserWarning: This function is deprecated, use smart_open.open instead. See the migration notes for details: https://github.com/RaRe-Technologies/smart_open/blob/master/README.rst#migrating-to-the-new-open-function
  'See the migration notes for details: %s' % _MIGRATION_NOTES_URL

In [88]:
def agregarfeature(archivo):

  
  #agrego longitud
  archivo['length']=archivo['text'].str.len()
  #vectorizo el text
  #vectorizer= CountVectorizer(max_features=40)
  #features=vectorizer.fit_transform(archivo['text']).todense()
  #txt_encode_frame=pd.DataFrame(features)
  #archivo[txt_encode_frame.columns]=txt_encode_frame

 
  
  archivo.drop(['text','id'], axis=1, inplace=True)
  
  #categorizo los null de keyword y location
  #archivo['keyword'].fillna('no keyword', inplace = True) 
  #archivo['location'].fillna('no location', inplace = True)

  #agrego longitud keyword y elimino keyword(despues tendria que mejorar eso)
  archivo['keyword'] = archivo['keyword'].str.replace('%20', ' ')
  archivo['keyword_length'] = archivo['keyword'].str.len()
  archivo.drop(['keyword'], axis=1, inplace=True)

   

  #limito los paises , solo aptos la cantidad de tweet mayor a 20


  #overtwentytweet = archivo.loc[:].groupby('location').agg({'location':'count'}).nlargest(10,'location')
  #overtwentytweet.columns=['canttweet']
  #dataovertwentytweet=overtwentytweet.reset_index()
  #dataovertwentytweet=dataovertwentytweet[dataovertwentytweet['canttweet']>15]
  #archivo=pd.merge(archivo,dataovertwentytweet,on='location',how='inner')

  #mean enconding location

 # archivo=archivo.groupby('location').agg(mean_encoding_location=('target','mean')).reset_index()
  #archivo.drop(['location'], axis=1, inplace=True)
  print('... sucessfull')

In [91]:
agregarfeature(train_3)

... sucessfull

In [92]:
def document_vector(word2vec_model, doc):
    acum_doc=list()
    for word in doc:
        if word in word2vec_model.vocab:
          acum_doc.append(word)
    return np.mean(word2vec_model[acum_doc], axis=0)

In [93]:
train_3['text_embbeding_prom']=train_3['clean_text'].apply(lambda x: document_vector(word2vec,x))

In [94]:
for lista in train_3['text_embbeding_prom']:
    cont=0
    for a in lista:
      cont=cont +1
      train_3[cont]=a

In [95]:
train_3.head(1)

     location  target  ...       299       300
0  Birmingham       1  ... -0.127965  0.159836

[1 rows x 306 columns]

In [99]:
#mean_enconding
train_3['mean_encoding_location']=train_3.groupby('location').agg(mean_encoding_location=('target','mean')).reset_index()['mean_encoding_location']
train_3

                           location  target  ...       300  mean_encoding_location
0                        Birmingham       1  ...  0.159836                     1.0
1     Est. September 2012 - Bristol       0  ...  0.159836                     0.0
2                            Africa       1  ...  0.159836                     1.0
3                      Philadelphia       0  ...  0.159836                     0.0
4                           Florida       0  ...  0.159836                     0.0
...                             ...     ...  ...       ...                     ...
7608                            NaN       1  ...  0.159836                     NaN
7609                            NaN       1  ...  0.159836                     NaN
7610                            NaN       1  ...  0.159836                     NaN
7611                            NaN       1  ...  0.159836                     NaN
7612                            NaN       1  ...  0.159836                     NaN

[7613 rows x 307 columns]

In [100]:
train_3.drop(['location'], axis=1, inplace=True)

In [101]:
train_3.drop(['clean_text'], axis=1, inplace=True)

In [102]:
train_3.drop(['text_embbeding_prom'], axis=1, inplace=True)

In [103]:
train_3.head(2)

   target  length  keyword_length  ...       299       300  mean_encoding_location
0       1      55             6.0  ... -0.127965  0.159836                     1.0
1       0      67             6.0  ... -0.127965  0.159836                     0.0

[2 rows x 304 columns]

In [104]:
target=train_3['target']

In [105]:
train_3.drop(['target'], axis=1, inplace=True)

In [106]:
train_3.head(1)

   length  keyword_length         1  ...       299       300  mean_encoding_location
0      55             6.0 -0.172481  ... -0.127965  0.159836                     1.0

[1 rows x 303 columns]

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
train_test_split(train_3, target, test_size=0.2, random_state=123)

In [ ]:
#xgboost colsample_bytree = 0.3, learning_rate = 0.01,
              #  max_depth = 4, alpha = 10, n_estimators = 10) 4.9 , sin embeding

In [140]:
xg_reg = xgb.XGBRegressor(objective ='reg:squarederror', 
                colsample_bytree = 0.3, learning_rate = 0.001,
                max_depth = 4, alpha = 10, n_estimators = 3)

In [141]:
xg_reg.fit(X_train,y_train)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.3, gamma=0,
             importance_type='gain', learning_rate=0.001, max_delta_step=0,
             max_depth=4, min_child_weight=1, missing=None, n_estimators=3,
             n_jobs=1, nthread=None, objective='reg:squarederror',
             random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
             seed=None, silent=None, subsample=1, verbosity=1)

In [142]:
preds = xg_reg.predict(X_test)

In [143]:
rmse = np.sqrt(mean_squared_error(y_test, preds))
print("RMSE: %f" % (rmse))

RMSE: 0.499952